---
name: merge-main

concurrency:
  group: merge-main
  cancel-in-progress: true

on:
  push:
    branches:
      - main

permissions:
    contents: read

jobs:

  # This job detects which parts of the repo have been changed, setting future jobs up for conditional behavior.
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.check.outputs.docs }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: check
        with:
          filters: |
            docs:
              - 'docs/**'
              - 'tb_pulumi/**.py'

  # Build the documentation and publish to Github Pages
  publish-docs:
    needs: detect-changes
    if: needs.detect-changes.outputs.docs == 'true'
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build docs
        shell: bash
        run: |
          # Install dependencies and build the HTML docs
          pip install .[dev]
          cd docs
          make clean html

          # Move the build files into a location where we can compile multiple build outputs
          mkdir -p _build/compiled_html/dark
          mv _build/html/* _build/compiled_html/

          # Build again with the dark theme
          TBPULUMI_DARK_MODE=yes make clean html

          # Move the dark theme files into a special directory
          mv _build/html/* _build/compiled_html/dark/

          # Compress for archival
          cd _build/compiled_html
          tar -cvjf ../../../docs.tbz ./*

      - name: Archive docs
        id: archive
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs.tbz

      # This publishes the built docs into a special git branch which we tell Github to use with Github Pages
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages  # this is the default, but let's be explicit
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/compiled_html/
          force_orphan: true